<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <PublishAot>true</PublishAot>
  </PropertyGroup>


	<ItemGroup>
		<Content Include="FFmpeg_bin\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="FFmpeg.AutoGen" Version="4.3.1" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dtimu.AvaPlayer\Dtimu.AvaPlayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FFmpeg_bin\" />
  </ItemGroup>
</Project>
